# Generated by Django 4.1.1 on 2023-01-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='home/cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='home/profile_pic/default.jpg', upload_to='home/profile_pic/'),
        ),
    ]
