# Generated by Django 4.1.1 on 2023-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.URLField(blank=True, default='https://www.intl-spectrum.com/articles/r75/ArticleDefault.jpg?x=528x372', max_length=1000000000000),
        ),
    ]
